import 'package:drift/native.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:go_router/go_router.dart';
import 'package:ourgarage/data/local/database.dart';
import 'package:ourgarage/data/repositories/database_holder.dart';
import 'package:ourgarage/features/household/household_migration_provider.dart';
import 'package:ourgarage/features/household/household_service.dart';
import 'package:ourgarage/features/household/widgets/join_household_screen.dart';

import '../../support/fake_auth_backend.dart';
import '../../support/fake_household_backend.dart';
import '../../support/fake_remote_garage.dart';

/// The path an App Reviewer follows from the review notes: an owner mints a
/// real invite code, and a second person types that exact code into "Join a
/// household" and gets in.
///
/// This cannot run against live Supabase — there is no `supabase` CLI,
/// Docker, or local Postgres available in this environment, so the
/// `accept_household_invite` SQL function itself is not exercised here (that
/// is what `supabase/tests/` is for, and it needs `supabase db reset` +
/// `psql` run by hand against a real project). What this test does verify is
/// everything on the Dart side of that boundary: [HouseholdService] generates
/// a code with the real [InviteCode] alphabet, and [JoinHouseholdScreen] —
/// the actual widget a user taps through, not a shortcut around it — accepts
/// that exact code and lands the joiner in the same household. The fake
/// household backend enforces the same rules the SQL function does (single
/// use, expiry, existence), so the two sides genuinely agree on the code, not
/// just on parameter shapes.
void main() {
  testWidgets(
    'a code generated by the owner is accepted by the joiner, end to end',
    (tester) async {
      final ownerHouseholdId = 'owner-household';

      // Shared by both "devices" in this scenario, exactly as it would be
      // shared by one Supabase project in reality: the invite the owner mints
      // has to be the invite the joiner redeems.
      final sharedBackend = FakeHouseholdBackend();

      // --- Owner side --------------------------------------------------
      // Not pre-seeded: this goes through the real generation path,
      // including InviteCode's alphabet and HouseholdService's collision
      // retry, so the code under test is the one actual code the app would
      // put in front of a user to read aloud or copy into the review notes.
      final code = await HouseholdService(
        sharedBackend,
      ).createInvite(ownerHouseholdId);

      expect(code, hasLength(6));
      expect(
        code.split('').every('23456789ABCDEFGHJKMNPQRSTUVWXYZ'.contains),
        isTrue,
        reason: 'must be typeable — none of the excluded 0/O/1/I/L characters',
      );

      final pending = await HouseholdService(
        sharedBackend,
      ).listInvites(ownerHouseholdId);
      expect(pending.single.code, code);
      expect(pending.single.isPending, isTrue);

      // --- Joiner side ---------------------------------------------------
      // Through the actual screen: typed character by character into the
      // real TextField, past the real input formatter, tapping the real
      // Join button — not a direct call into JoinHouseholdService. This is
      // the same UI path a reviewer following the review notes drives.
      final db = AppDatabase.forTesting(NativeDatabase.memory());
      DatabaseHolder.overrideWith(db);
      addTearDown(() async {
        DatabaseHolder.overrideWith(null);
        await db.close();
      });

      final joinerAuth = FakeAuthBackend(userId: 'joiner-1');
      await joinerAuth.signInWithAppleIdToken(idToken: 't', rawNonce: 'n');

      final router = GoRouter(
        initialLocation: '/join',
        routes: [
          GoRoute(
            path: '/',
            builder: (_, _) => const Scaffold(body: Text('vehicle list')),
          ),
          GoRoute(
            path: '/join',
            builder: (_, _) => const JoinHouseholdScreen(),
          ),
        ],
      );

      await tester.pumpWidget(
        ProviderScope(
          overrides: [
            fakeAuthServiceOverride(joinerAuth),
            householdServiceProvider.overrideWith(
              (ref) => HouseholdService(sharedBackend),
            ),
            fakeRemoteGarageOverride(FakeRemoteGarage()),
          ],
          child: MaterialApp.router(routerConfig: router),
        ),
      );
      for (var i = 0; i < 10; i++) {
        await tester.pump(const Duration(milliseconds: 50));
      }

      // The joiner has an empty local garage, so no upload/keep-local choice
      // is expected — straight through to success.
      await tester.enterText(find.byType(TextField), code);
      for (var i = 0; i < 10; i++) {
        await tester.pump(const Duration(milliseconds: 50));
      }
      await tester.tap(find.widgetWithText(FilledButton, 'Join'));
      await tester.runAsync(() async {
        await Future<void>.delayed(const Duration(milliseconds: 300));
      });
      for (var i = 0; i < 10; i++) {
        await tester.pump(const Duration(milliseconds: 50));
      }

      expect(
        find.textContaining('You’ve joined the household'),
        findsOneWidget,
      );
      expect(find.text('vehicle list'), findsOneWidget, reason: 'navigated away');

      // The membership the SQL function would have created is, on the fake,
      // recorded against the same household the code was minted for — the
      // one property the fake and the real RPC must agree on for this test to
      // mean anything.
      final members = await HouseholdService(
        sharedBackend,
      ).listMembers(ownerHouseholdId);
      expect(members.map((m) => m.userId), contains('joiner-1'));

      // Single-use: the code the owner is showing on their screen right now
      // must not work a second time for someone else.
      final invites = await HouseholdService(
        sharedBackend,
      ).listInvites(ownerHouseholdId);
      expect(invites.single.isPending, isFalse);

      await tester.pumpWidget(const SizedBox.shrink());
      await tester.pump(Duration.zero);
    },
  );
}
